# TENSORFLOW'S HELLO WORLD

## In this Notebook I tried to complete "HELLO WORLD!" of tensorflow 

## How to Build a graph in TensorFlow ??




In [ ]:
%tensorflow_version
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


Currently selected TF version: 2.x
Available versions:
* 1.x
* 2.x
Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
graph1 =tf.Graph()

## BASICS

In [ ]:
with graph1.as_default():

    a = tf.constant([2], name = 'filthy_a')
    b = tf.constant([3], name = 'filthy_b')
    #c = tf.constant([10.0],dtype=float,name='filthy_c',shape=(1,2))
    c = tf.constant([16.2],dtype=float,name='filthy_c',shape=(1,3))

In [ ]:
# Printing the value of a
sess = tf.Session(graph = graph1)
result = sess.run(c)
print(result)
sess.close()

[[16.2 16.2 16.2]]


## BUILD BASIC ELEMENTS

In [ ]:
graph3=tf.Graph()
with graph3.as_default():

  scalar = tf.constant([1], name = 'scalar_filthy')
  vector = tf.constant([1,2,3,4,5], name  = 'vector_filthy')
  matrix = tf.constant([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]], name= 'matrix_filthy')
  tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] , name = 'tensor_filthy')

with tf.Session(graph=graph3) as sess:
  print('see the scalar by tensorflow:\n %s \n' % sess.run(scalar))
  print('see the vector by tensorflow:\n %s \n' %  sess.run(vector))
  print('see the matrix by tensorflow:\n %s \n' %  sess.run(matrix))
  print('see the tensor by tensorflow:\n %s \n' %  sess.run(tensor))
  print('see the scalar shape by tensorflow:\n %s \n' % scalar.shape)
  print('see the vector shape by tensorflow:\n %s \n' %  vector.shape)
  print('see the matrix shape by tensorflow:\n %s \n' %  matrix.shape)
  print('see the tensor shape by tensorflow:\n %s \n' %  tensor.shape)

see the scalar by tensorflow:
 [1] 

see the vector by tensorflow:
 [1 2 3 4 5] 

see the matrix by tensorflow:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

see the tensor by tensorflow:
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 

see the scalar shape by tensorflow:
 (1,) 

see the vector shape by tensorflow:
 (5,) 

see the matrix shape by tensorflow:
 (3, 5) 

see the tensor shape by tensorflow:
 (3, 3, 3) 



## Arithematic Operations

In [ ]:
graph3 = tf.Graph()

with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
    Matrix_three = tf.constant([[3,5,5],[6,6,6],[8,9,10]])

    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

    subtract_1_operation = tf.subtract(Matrix_one,Matrix_three)
    subtract_2_operation = Matrix_one - Matrix_three


with tf.Session(graph =graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)
    result = sess.run(subtract_1_operation)
    print ("Defined using tensorflow expressions :")
    print(result)
    result = sess.run(subtract_2_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using tensorflow expressions :
[[-2 -3 -2]
 [-4 -3 -2]
 [-5 -5 -5]]
Defined using normal expressions :
[[-2 -3 -2]
 [-4 -3 -2]
 [-5 -5 -5]]


## VARIABLES

### Example - 1

In [ ]:
v = tf.Variable(0)

In [ ]:
update = tf.assign(v, v+1)

In [ ]:
init_op = tf.global_variables_initializer()

In [ ]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(10):
        session.run(update)
        print(session.run(v))

0
1
2
3
4
5
6
7
8
9
10


## PLACEHOLDERS

In [ ]:
a = tf.placeholder(tf.float32)

In [ ]:
b = a * 2

In [ ]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)

7.0


In [ ]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]
